//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppDatosAbiertos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatosAbiertosEntities : DbContext
    {
        public DatosAbiertosEntities()
            : base("name=DatosAbiertosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ConjuntodeDato> ConjuntodeDato { get; set; }
        public virtual DbSet<Mes> Mes { get; set; }
        public virtual DbSet<RecursoClorogasSulfato> RecursoClorogasSulfato { get; set; }
        public virtual DbSet<RecursoCResidual> RecursoCResidual { get; set; }
        public virtual DbSet<RecursoNomina> RecursoNomina { get; set; }
        public virtual DbSet<RecursoPrestServicios> RecursoPrestServicios { get; set; }
        public virtual DbSet<RecursoProdAgua> RecursoProdAgua { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
