//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppDatosAbiertos
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class RecursoCResidual
    {
        public int IdRecursoCResidual { get; set; }
        public int IdConjunto { get; set; }
        [Display(Name = "Año")]
        public int Anio { get; set; }
        public int IdMes { get; set; }
        [Display(Name = "Puerto plata")]
        public decimal AcPuertoPlata { get; set; }
        [Display(Name = "Sosua")]
        public decimal AcSosua { get; set; }
        [Display(Name = "Montellano")]
        public decimal AcMontellano { get; set; }
        [Display(Name = "La isabela")]
        public decimal AcLaIsabela { get; set; }
        [Display(Name = "Altamira")]
        public decimal AcAltamira { get; set; }
        [Display(Name = "Luperon")]
        public decimal AcLuperon { get; set; }
        [Display(Name = "Los Hidalgos")]
        public decimal AcLosHidalgos { get; set; }
        [Display(Name = "Guananico")]
        public decimal AcGuananico { get; set; }
        [Display(Name = "Imbert")]
        public decimal AcImbert { get; set; }
    
        public virtual ConjuntodeDato ConjuntodeDato { get; set; }
        public virtual Mes Mes { get; set; }
    }
}
