//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppDatosAbiertos
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class RecursoProdAgua
    {
        public int IdRecursoPAgua { get; set; }
        
        public int IdConjunto { get; set; }
        [Display(Name = "Año")]
        public int Anio { get; set; }
        
        public int IdMes { get; set; }
        [Display(Name = "Galones por mes")]
        public decimal GalonesxMes { get; set; }
        [Display(Name = "Metro cúbico por mes")]
        public decimal Mts3Mes { get; set; }


       
        public virtual ConjuntodeDato ConjuntodeDato { get; set; }
        public virtual Mes Mes { get; set; }
    }
}
